### ISSUE TITLE
Any chances to get piomxtextures_pocplayer_widget work?

### ISSUE THREAD

**Issue by sagiadinos** [carlonluca/pot#69]
Hello Luca,

I compiled piomxtextures_pocplayer_widget with last binaries (POT 5.7.0 with Qt 5.10.0) and try to start a video. No error occurs, but video did not play and it shows a white screen with a red rect.
The QML based piomxtextures_pocplayer works fine.

Did I miss something or is there no QWidget support?

Kind regards

**Comment by carlonluca** [comment]
Yes, no support for widgets. I don't think it makes sense to spend time on implementing this for widgets nowadays, so I don't think I'll do, sorry.

**Comment by sagiadinos** [comment]
Hello,
thank you for answering. No need for sorry it is understandable ... unfortunately it makes sense for me. ;).
Kind regards
