### ISSUE TITLE
Render Camera Preview Video into QT

### ISSUE THREAD

**Issue by gurtajs4** [carlonluca/pot#71]
Hi Luca,

Thanks for such a nice library and sample application.
I am planning to use POT for rendering live video from Raspberry PI Camera along with some overlay on top of Video Feed.

Ideally this should be possible? 
Can you give me some idea on how this can be achieved... 
I am planning to use https://github.com/gagle/raspberrypi-omxcam which can provide data from camera in h264/RGG/YUV format.

Thanks

**Comment by carlonluca** [comment]
Hello,
it should be possible. There probably is a camera component. I've never used it anyway, sorry.
